package task12_transportation_XML_paser_and_export_to_file.transportation.repo;

import task12_transportation_XML_paser_and_export_to_file.common.business.repo.CommonRepo;
import task12_transportation_XML_paser_and_export_to_file.transportation.domain.Transportation;

public interface TransportationRepo extends CommonRepo<Transportation, Long> {
}
